### ISSUE TITLE
Hostfile missing with general script

### ISSUE THREAD

**Issue by pagrubel** [lanl/BEE#1]
When using an mpi script the hostfile is created with the correct number of slots etc. However the mpiscript option is not general enough. So to run an mpi program multiple times with different inputs or a different number of ranks I used the general script. (I'm not even sure you can run with inputs for mpi with the built in mpi script functionality). The hostfile did not exist so it did not work. My workaround was to make my own hostfile in my shared directory and copy it to root in my general script before I ran the mpi program. This should be a feature with the general script like it is for the mpi script. Here is a copy of my hostfile for running on 8 nodes with 16 cores each.  

lammps-bee-master slots=16 
lammps-bee-worker001 slots=16 
lammps-bee-worker002 slots=16 
lammps-bee-worker003 slots=16 
lammps-bee-worker004 slots=16 
lammps-bee-worker005 slots=16 
lammps-bee-worker006 slots=16 
lammps-bee-worker007 slots=16

**Comment by JieyangChen7** [comment]
Yes. I believe replace all of them should work just fine.

**Comment by pagrubel** [comment]
I’ll do that Monday ~Pat
On Apr 20, 2018, at 9:16 PM, Jieyang Chen <notifications@github.com> wrote:

Yes. I believe replace all of them should work just fine.

**Comment by pagrubel** [comment]
This issue has been fixed. Will open an issue to look at os.gituid and os.getguid as well as what else may cause problems with os

Pull request #6
