### ISSUE TITLE
Create VASP Charliecloud container

### ISSUE THREAD

**Issue by trandles-lanl** [lanl/BEE#144]
- [x] Identify version of VASP
- [x] Get compile-time build options for VASP
- [x] Identify any other required software for the container
- [x] Build VASP Charliecloud container
  - [x] x86_64
  - [ ] Power9(?)
  - [ ] GPU support(?)
- [x] Test VASP Charliecloud container
  - [x] on fog
  - [x] on darwin (x86_64 and Power9(?))
  - [ ] on kodiak (GPU) (?)

**Comment by pagrubel** [comment]
@Boogie3D You can check some of the items off above and/or close this.

**Comment by Boogie3D** [comment]
* Version: 5.4.4
* Other required software: ScaLAPACK
* Compiled on Darwin x86_64
* Tested on Fog and Darwin x86_64

**Comment by pagrubel** [comment]
This is very old and we do have some container build recipes in gitlab so I'm closing it
