### ISSUE TITLE
Develop BEE Resource Monitor

### ISSUE THREAD

**Issue by guanxyz** [lanl/BEE#156]
Creating an issue for discussing and summarizing the design spec (combining #115 and #98).

**Generally problem  we are looking to solve:**
![Workflow_01](https://user-images.githubusercontent.com/3259304/80981121-84a3fe80-8df7-11ea-86a7-1483ddfaf8f2.png)

** General BEE
![Untitled (Draft)-3](https://user-images.githubusercontent.com/3259304/81217170-266b4d00-8faa-11ea-93aa-65509a8d052b.jpg)

**The overall system we are looking at (_MARS_ is our scheduler)**
![Policy](https://user-images.githubusercontent.com/3259304/80981227-adc48f00-8df7-11ea-881e-92cc9fbd0a22.png)

**General functions**
![System-Overview2](https://user-images.githubusercontent.com/3259304/80981298-c92f9a00-8df7-11ea-931d-2e4789828b95.png)

**TM-RM: Interface between TM and RM (SLURM, AWS, GCP, et al)**
- Mapper of SLURM Commands: sinfo, squeue, srun, .... (need verifications for which commands should be added). Currently considering of pyslurm. More details should be defined: "sinfo -> bee-sinfo"
![arch](https://user-images.githubusercontent.com/3259304/80981843-802c1580-8df8-11ea-8b92-fe6088133194.gif)

Discussion will continue....

**Comment by rstyd** [comment]
This issue no longer fits BEE's scope. Closing pending @pagrubel evaluation

**Comment by pagrubel** [comment]
I hate to take this off the list of things to do. In some ways it does fit a larger future vision. We can close it with a caveat to revisit it if BEE is able to run across platforms at multiple sites.
