### ISSUE TITLE
crt_drivers.py: singularity driver ignores entrypoint.sh

### ISSUE THREAD

**Issue by qwofford** [lanl/BEE#202]
I believe we should assume that users prefer `singularity run` over `singularity exec`. Singularity run offers more comprehensive environment configuration for the container. Specifically, a singularity "run" will run the Dockerfile entrypoint (often entrypoint.sh). A singularity "exec" will simply run the next argument in the container, which can skip important path setting established in entrypoint.sh. The singularity way would be to create a case in entrypoint.sh to catch the binary you're trying to execute.

**Comment by rstyd** [comment]
Closing this issue since it's not really a concern anymore.
