### ISSUE TITLE
Create set of synthetic canonical HPC workflows

### ISSUE THREAD

**Issue by mcpherson** [lanl/BEE#251]
I'm working on this but want to capture it as an issue.

We need to define a set of canonical HPC workflows that represent the kinds of problems that LANL runs. They should be defined somewhat abstractly (e.g. run a simulation generating time step files, collect files, make movie, etc.). For each workflow we should:

- Document the workflow (maybe as `README`s  or in a wiki page)
- Decide where to put these in our repo (as tests?)
- Create a representative set of CWL files
- Enumerate the specific CWL features required for this workflow (e.g. `ScatterFeatureRequirement`)
- Explore CWL approaches that eliminate difficult requirements (e.g. `InlineJavascriptRequirement`)
- Create synthetic codes to test the workflow (i.e. simple codes that mimic the actual workflow steps)
- Synthetic codes should produce *realistic artifacts* (e.g. CPU load for specified time, output files, etc.)
- Create Docker and Charliecloud versions of the synthetic codes
- Ensure that the CWL validates with `cwltool`
- Ensure that the synthetic workflow runs with `cwltool`
- Initially avoid complicating factors (such as MPI) so that these can be tested and run anywhere

These canonical workflows can then be used to investigate specific paths in `cwltool` with an eye towards using it (or not) as a piece of our parsing solution.

As a first step we could start with CLAMR (@trandles-lanl is writing CWL, I can write synthetic codes) and Sven's workflows (I started looking at this). But soon, we should start a discussion with the weapons program to capture real world workflows.

Once we have these, we can use to develop and test the rest of the system (using a parser if possible or, at least initially, by manually constructing the workflows).

**Comment by pagrubel** [comment]
@Boogie3D This seems outdated can it be closed?

**Comment by pagrubel** [comment]
Closing this outdated issue
