### ISSUE TITLE
cli: Separate GDB and restd from cli

### ISSUE THREAD

**Issue by qwofford** [lanl/BEE#276]
I believe we should consider using the cli to launch external scripts rather than launching them directly.

One reason we might do that is to separate concerns; the cli could become a launch coordinator rather than a collection of launch scripts.

Another reason we might do this is to make logging cleaner. If the gdb and restd launch scripts become separate `.py` scripts, then we only have to use one logger for all bee components. Currently, we require 3 different loggers to support keeping gdb and restd launches in the same cli script.

**Comment by rstyd** [comment]
Resolved by #311
