### ISSUE TITLE
build: Dockerfile for build system

### ISSUE THREAD

**Issue by qwofford** [lanl/BEE#292]
Via discussions in Mattermost BEEDev channel:

1. We can and should assume that a supported container runtime exists on the host: Charliecloud or Singularity to start.
2. We should deploy a build container for the user that resolves all dependencies related to a given set of supported runtimes.
3. The recipe for that container should live in the data directory of the beeflow project.
4. That recipe should create a container which may be deployed and used to build all workflow task containers on the system.

**Comment by pagrubel** [comment]
@qwofford This seems done at least for Charliecloud should it be closed?

**Comment by pagrubel** [comment]
@qwofford Is this done?
