### ISSUE TITLE
beeflow needs a 'kill' option

### ISSUE THREAD

**Issue by rstyd** [lanl/BEE#306]
BEEStart needs a --kill option to kill all the processes it starts. Currently, there's no good way to kill all the processes BEEStart spawns other than manually killing processes after a `ps` call. This could be implemented pretty easily by just going through all the current pid files created during start and killing those processes.

**Comment by pagrubel** [comment]
@rstyd Is this the same as #402, can we combine them and close one

**Comment by rstyd** [comment]
Yes. I'll do that.

**Comment by pagrubel** [comment]
``beeflow stop`` has been implemented
