### ISSUE TITLE
build: Build interface integration

### ISSUE THREAD

**Issue by qwofford** [lanl/BEE#326]
Creating this issue to track work toward integrating `beeflow --build` in the BEE system.

So far we've discussed the following major points toward scheduler:builder interface integration:
* We discussed whether the builder should execute on the front-end (task manager node), the workflow manager node, or the compute nodes within a front-end domain (task manager domain). Long term we decided that we should execute build tasks on compute nodes, but given current network constraints on LANL systems, we will run build commands on the front-ends for now.
* We discussed how build instructions should be processed: pre-process or pre-workflow. We decided that each BEE task will necessarily have a build pre-task to resolve the environment before executing a task. That means that all defined BEE tasks will generate exactly 2 jobs for the scheduling system: the build pre-task and the task.  Given then previous comment about build tasks on front-ends, the initial integration may not use the scheduling system at first.
* We discussed how to archive the results of a build pre-task. We decided (IIRC) that archiving a build task formally is not a concern because the container archive will include all containers that were successfully generated by a build pre-task. In the event of failure, the BEE logs will show how the build pre-task failed. 
* We discussed when the builder task should be invoked. I'm currently thinking this should happen before the `submit_jobs()` call in `task_manager.py`: https://github.com/lanl/BEE_Private/blob/56b4214d7dafec7e3a24ca72069fee7dde936fe9/src/beeflow/task_manager.py#L186-L189 Specifically, I'm thinking there should be three functions within `process_queues`: `resolve_environment()`, then `submit_jobs()`, and finally `update_queues()`. There may be some code movement involved, but this is my current strategy. This strategy will change when we move build tasks to compute nodes.

Another point we haven't mentioned is whether _all_ build tasks should happen on compute nodes. For instance, perhaps dockerPull should occur on the front end, and only dockerFile (build from Dockerfile) should be scheduled as a job.

**Comment by pagrubel** [comment]
@qwofford the build PR has been merged, does that satisfy this issue?
Can we close this issue?

**Comment by qwofford** [comment]
Yep! This can be closed. Build tasks happen on the front-end, and until they need to happen on compute nodes, we're good to go.
