### ISSUE TITLE
build: Builder should allow flexible container archive directory

### ISSUE THREAD

**Issue by qwofford** [lanl/BEE#329]
Right now, builder assumes `bee_workdir` is the base for container archive tarballs. Since these containers can be >20GB, we would like to be able to control where the container archive exists separately from the bee_workdir.

Suggested resolution is, on the first launch of `bee_interface.py`, check for config location of container_archive, if not exist, set up defuault and write to config. User can go back in and change later if desired.

Note to self, don't forget documentation!

**Comment by pagrubel** [comment]
Need to make sure this is complete including documentation then close it. Adding to Public Release and assinging myself

**Comment by pagrubel** [comment]
Closing this since the user can change the container archive location in bee.conf
