### ISSUE TITLE
config: Clean up configuration defaults

### ISSUE THREAD

**Issue by qwofford** [lanl/BEE#334]
Creating an issue to track some config default issues that are popping up for me with a fresh installation of BEE.

1. GDB default path to neo4j container is not valid for Fog.
2. Investigating possible issue with bee.conf being created in multiple places. The correct default placement is `~/.config/beeflow/bee.conf`

**Comment by pagrubel** [comment]
Adding this to Public Release board. The last time I tried this it did not populate the config file well. At a minimum we need to document examples of a usable config file.

**Comment by pagrubel** [comment]
@jtronge Is this what you were working on as far as the config goes

**Comment by jtronge** [comment]
I think this is more related to setting the config defaults within the modules. But I think the second item that Quincy mentions, "Investigating possible issue with bee.conf being created in multiple places" might be related to the bug I've run into.

**Comment by pagrubel** [comment]
@jtronge Is there an issue for the bug? If not would you create one and put it on the release project board.

**Comment by jtronge** [comment]
Yeah, issue #405. I think it's on there.

**Comment by pagrubel** [comment]
I'm closing this. I'll create one just for the bee.conf file with defaults.
