### ISSUE TITLE
Better Error Message with no Slurmrestd

### ISSUE THREAD

**Issue by rstyd** [lanl/BEE#342]
We need to provide a better error message when slurmrestd isn't running.

**Comment by rstyd** [comment]
BEE uses slurmrestd to make HTTP requests to slurm's REST interface. Currently, there is no easy to understand error when slurmrestd is not available. We need some proper error handling for that case. 

The slurm worker is the piece of code that actually uses this REST interface. You can find it at `beeflow/common/worker/slurm_worker.py`.  We create a socket then connect to slurmrestd with it using the requests_unixsocket library. 

We need to 
1) Provide an error when slurmrestd isn't available. 
and 
2) Come up with a plan for how to remediate that error. 

For 2), we could just leave it to the user to start up slurmrestd themselves in case there's an issue with it or actually launch slurmrestd in the slurmworker. What do you think about that @pagrubel? 

I think two is probably the best option but we'll also have to handle what to do if slurmrestd can't run for some reason.

**Comment by pagrubel** [comment]
Aren't there two scenarios? I recall one where slurmrestd wasn't available because of the installation of slurm (or am i remembering this  wrong).
If starting up slurmrestd can be done I would think we should try doing it automatically

**Comment by rstyd** [comment]
Yes. That's another point I'll tweak what I wrote.

**Comment by pagrubel** [comment]
Closing this since we now run without slurmrestd if it is not available.
