### ISSUE TITLE
Packaging: clean up data directory

### ISSUE THREAD

**Issue by qwofford** [lanl/BEE#345]
Making a suggestion to move neo4j workflows to top level, following packaging guidance from PyPA and Serious Python.

If I recall correctly, we should limit depth so that directories are only added to a project when multiple files are contained within them. README files should describe the files of the CWD as well as any context required to understand them. Subdirectories will also contain README's which describe files. README's may optionally describe subdirectories in the CWD.

For example:
* `src/beeflow/data/README.md`: Describes all of the files it contains, but may or may not describe the subdirectories, such as `neo4j`. No guidance on subdirectory description, IIRC, but seems like a good idea.
* `src/beeflow/data/neo4j/README.md`: Describes the common attributes of the files contained, in this case the README would describe that each of these files are workflow files.

I also saw an empty directory for CWL workflows. Perhaps those would fit into the existing: https://github.com/lanl/BEE_Private/tree/develop/src/beeflow/data/cwl ?

**Comment by pagrubel** [comment]
This issue was solve with #390
