### ISSUE TITLE
Implement CWL Runtime Specifications

### ISSUE THREAD

**Issue by Boogie3D** [lanl/BEE#351]
With a CWL parser nearly finished, we still need to implement remaining general CWL runtime specifications in either the Workflow Interface, Task Manager, and/or Workflow Manager in order for a BEE workflow to fully and properly run. This includes:
- [x] Constructing and scheduling/executing a `Task` command
- [x] Output file coalescing, i.e. `glob`
- [x] Capturing `stdout` in a file when applicable
- [x] Runtime parameter substitution, e.g. `glob: $(inputs.output_file_name)`
- [x] Checking for step input `default` value if input isn't satisfied at runtime
- [x] Data flow between tasks

**Comment by pagrubel** [comment]
@Boogie3D is the checklist above correct?

**Comment by pagrubel** [comment]
@Boogie3D should this issue be closed?

**Comment by Boogie3D** [comment]
@pagrubel I believe so
