### ISSUE TITLE
beeflow: Make sure all pylama ignore comments are OK

### ISSUE THREAD

**Issue by qwofford** [lanl/BEE#358]
There are many pylama rules which are ignored. These are either ignored in-line after the line, or more commonly, the list of rules ignored is at the bottom of the file. 

Before we release beeflow in any capacity, we should have a critical review of these exceptions, and whether they are acceptable or whether we should fix them.

**Comment by pagrubel** [comment]
Agree this should be done as well as a sweep of files for compliance before any public release.
