### ISSUE TITLE
Need cwl files for singularity & summit that work with the new parser

### ISSUE THREAD

**Issue by pagrubel** [lanl/BEE#389]
CWl files for singularity and summit using the generalized parser are needed.

Also as part of this issue, I plan to clean up the cwl files in data. 
Do we need to keep the no-yaml examples?

**Comment by pagrubel** [comment]
I decided to keep the no_yaml files but they needed fixing for the new parser

**Comment by Boogie3D** [comment]
PR #390 was merged, closing this.
