### ISSUE TITLE
Shutting down BEE components and cleaning up

### ISSUE THREAD

**Issue by pagrubel** [lanl/BEE#402]
I think we need to look at what needs to be cleaned up as portions of BEE are run. For instance most super computer systems have multiple front ends that are assigned in some manner to the user. What are we leaving behind. I guess this also brings up the issue of where our modules will be running.

**Comment by pagrubel** [comment]
We do now have the beeflow stop & status functions. Are there any other cleanup considerations?  tmp files, sockets?

**Comment by jtronge** [comment]
The GDB isn't cleaned up with this. Since it needs to be started by the WFM (and we'll have to start multiple for multiple workflows) it makes it a little difficult to cleanup.

**Comment by pagrubel** [comment]
Should be fixed with the multiple workflows PR
We can leave the slurm socket file- Rusty says it's okay to leave that.

**Comment by pagrubel** [comment]
@rstyd refer to the PR that fixes this

**Comment by pagrubel** [comment]
There are some things that still need to be cleaned up for example:

pagrubel  356811  0.2  1.1 47158628 3069504 ?    Sl   Oct31   3:16 /usr/local/openjdk-8/bin/java -cp /var/lib/neo4j/plugins:/var/lib/neo4j/conf:/var/lib/neo4j/lib/*:/var/lib/neo4j/plugins/* -server -XX:+UseG1GC -XX:-OmitStackTraceInFastThrow -XX:+AlwaysPreTouch -XX:+UnlockExperimentalVMOptions -XX:+TrustFinalNonStaticFields -XX:+DisableExplicitGC -Djdk.tls.ephemeralDHKeySize=2048 -Djdk.tls.rejectClientInitiatedRenegotiation=true -Dunsupported.dbms.udc.source=tarball -Dfile.encoding=UTF-8 org.neo4j.server.CommunityEntryPoint --home-dir=/var/lib/neo4j --config-dir=/var/lib/neo4j/conf
List slurm socket and gdb files if any in /ram/tmp:
srwxrwxr-x  1 pagrubel       pagrubel            0 Oct 31 10:04 slurm_pagrubel_3882.sock

**Comment by rstyd** [comment]
- Neo4j instance should _now_ be killed with an upcoming push to the multiple workflows PR. 
- Slurm socket should be fine. 
- I'll check on GDB files in /ram/tmp.
