### ISSUE TITLE
BeeConfig Instances

### ISSUE THREAD

**Issue by jtronge** [lanl/BEE#405]
When loading up components of BEE, multiple instances of the BeeConfig class are getting created. Because of this, configuration within a single component is not the same.

As an example, in the Task Manager, one BeeConfig instance gets created in that particular script, then when the container runtime code is imported, another instance gets created in that code, then more instances are created in other submodules (in different parts of the `common/` package). If somebody needs to use a different bee.conf file for some reason, I've noticed that some parts of the code load the correct config file, while other parts load the old configuration file and then some parts don't work as they should.

I'm thinking that we may want to turn the BeeConfig class into some sort of "singleton" object or implement configuration loading at a module level, so that configuration is consistent. So for example, we'd want to initialize the config in only one place (the `wf_manager.py` script, the `task_manager.py` script, etc.) and then other modules would only need to import the BeeConfig module to get the correct config values.

**Comment by pagrubel** [comment]
I'm still a little confused. When you say "we'd want to initialize the config in only one place (the wf_manager.py script, the task_manager.py script, etc.) " Do you mean in only one place per each module (task manager, wf manager etc.)?

**Comment by jtronge** [comment]
I think we'd want to do these once per process (so once per task manager, wf manager, scheduler, etc) rather than per module. So we'd only have this code chunk once in the main script file, rather than in each module file: 

```
if len(sys.argv) >= 2:
    bc = BeeConfig(userconfig=sys.argv[1])
else:
    bc = BeeConfig()
```
The big issue right now is that when we load the task manager or the wf manager, these objects are getting created in different modules throughout the `common/` directory, and the same chunk of code above is copied to many of those modules. Sometimes however they aren't loading the right configuration file. So if I change some config options under the `[charliecloud]` configuration, one module might see that change, but another won't if they don't load the config in exactly the same way.

To avoid this, I'm thinking we should only run that code once, in each main script that gets run.
This shouldn't change the way that BEE is configured (so if we want the a different configuration per wf manager or task manager, etc. that would still work).

**Comment by pagrubel** [comment]
@jtronge you mentioned in the meeting that this causes bugs. Should we add the bug label?

**Comment by pagrubel** [comment]
@jtronge Is work on this issue completed?

**Comment by jtronge** [comment]
Yes this can be closed.
