### ISSUE TITLE
Improve BEE CLI Client

### ISSUE THREAD

**Issue by rstyd** [lanl/BEE#416]
Develop a new version of the current BEE CLI that leverages features from the GUI client.
 
It will:
* Be non-interactive and behave like a standard unix tool
* Provide methods to access remote computing resources
    * These will include ssh tunneling and suppor auth methods that require user input such as cryptocards and RSA keys
* Use the same sqlite3 db as the GUI client to keep track of workflows and provide data persistence
    * The two should be compatible to the point where one can submit a job with the CLI then check on the status later with the GUI

**Comment by pagrubel** [comment]
Adding this to the Public Release project board but we need to decide what parts we want to do just for the release.

**Comment by rstyd** [comment]
Needs to incorporate #439

**Comment by pagrubel** [comment]
@rstyd If this is inprogress please move it on the board

**Comment by pagrubel** [comment]
@rstyd Did #445 satisfy this Issue? Should we close it?
