### ISSUE TITLE
Set Up CI

### ISSUE THREAD

**Issue by pagrubel** [lanl/BEE#419]
Get ready for CI when the repo goes public
Start gathering requirements

**Comment by jtronge** [comment]
I think we will probably need a couple different CI workflows to run:

* Some sort of integration test, that runs complete workflows with BEE (such as the CLAMR example) and then records the results
* Unit tests/general testing matrix - I'm guessing we would simply install BEE here and then run pytest

We may need some more, but I think these two are a good start. Both of these should be able to work with GitHub Actions, if that is the route we want to go.

Also, we should decide when these are run. For instance, do we want these to run when a developer opens a PR into develop? Do we want them to run on every merge as well? There are other possibilities as well.

**Comment by pagrubel** [comment]
@jtronge would you like to add what else needs to be done for this or should we close this issue

**Comment by jtronge** [comment]
I'll go ahead and close this, if that's ok. We'll probably need to make some more updates to the CI, but those are probably better off with new issues.
