### ISSUE TITLE
Change Workflow ID

### ISSUE THREAD

**Issue by pagrubel** [lanl/BEE#422]
From Public Release discussion (Rusty):
We had discussed changing the workflow IDs to make them more readable. Currently we’re using UUIDs.
I did a little bit of googling and found this page with a nice discussion about IDs: https://gnugat.github.io/2018/06/15/short-identifier.html.
I like their idea of using the first few characters of a SHA256 hash the same way that git does.

From previous discussion(Tim):
I think the WorkflowID (WfID?) should be something meaningful and easy for a human to interpret. Alternatively, if the WfID is something ugly like a git commit hash, BEE should implement a way of mapping that to a human-friendly representation. Some random ideas for WfID:

name-date where name is supplied by the user via the client and date is provided by BEE in the format YYYYMMDDHHMM. An example would be VASP-SnO-202005061201.
UUID where UUID is created by BEE using python's uuid.uuid4() function. BEE would allow a user to refer to this workflow in the same manner as git does:

**Comment by rstyd** [comment]
- Client needs to know how many characters to truncate the ID by
    - List REST end point needs to give an integer with the truncate length
- List endpoint returns WF metadata along with IDs
    - Will now also return a truncation value which tells the client how many characters to truncate the IDs by
    - Client will list truncated IDs
    - When user enters ID, client will use String.startswith() to find the right ID. 
    - STRETCH GOAL: If client can't find right ID, inform the WFM which will increment the truncation value
