### ISSUE TITLE
Modify CWL Interface to Support Checkpointing 

### ISSUE THREAD

**Issue by rstyd** [lanl/BEE#451]
We need to add a new requirement similar to the beeflow:MPIRequirement. 
I'm thinking we'll call it beeflow:CheckpointRequirement, but I'm open to other suggestions. 

It will have these parameters: 
    - enabled: \<`true` or `false`\>
    - checkpoint_path: \<Path to directory containing checkpoint files\>
    - checkpoint_regex: \<Regex for the checkpoint files\>
    - restart_parameters: \<parameter used for restarting the application with the checkpoint file\>
    - num_tries: \<The number of restarts to attempt\>

**Comment by pagrubel** [comment]
Again I think we need checkpoint parameter also for clamr there are two linked files to the latest checkpoints backup0.crx to the latest and backup1.crx to the one before. The Task Manager could check for the existence of a list in an ordered list by priority, check for the first, if it doesn't exist, check for the next.

**Comment by pagrubel** [comment]
This was satisfied in #458
