### ISSUE TITLE
Create New Checkpointing CLAMR Workflow

### ISSUE THREAD

**Issue by rstyd** [lanl/BEE#452]
We need to create a modified version of the CLAMR workflow that supports checkpointing. 
We can enable checkpointing in CLMAR with the `-c n` parameter where `n` means write a checkpoint to disk every `n` time steps. 
This workflow will depend on the new Checkpoint requirement that will be implemented with #451. 

Here is what I'm currently thinking the CheckpointRequirement will look like within the CWL file:

```
beeflow:CheckpointRequirment
  enabled: true
  file_path: checkpoint_output
  file_regex: backup[0-9]*.crx
  restart_parameters: -R $(checkpoint_file)
  num_tries: 3
```

**Comment by pagrubel** [comment]
Will this be another thing we will need to use jinja job templates for. I would only imagine there are many ways to checkpoint and to restart. But for clamr it works to add -c n (100 works fine for our example) to the run command for checkpointing and -R checkpoint_output/backup0.crx to the original command to restart.

**Comment by pagrubel** [comment]
So I think we may need to add to the above cwl (perhaps a list of parameters)
checkpoint parameter: -c <int>

**Comment by pagrubel** [comment]
Okay I was think about this wrong the -c goes in the original cwl
