### ISSUE TITLE
Jinja Submit Template Lmod 

### ISSUE THREAD

**Issue by rstyd** [lanl/BEE#460]
The jinja submit template is currently not working correctly with lmod. It uses `srun` before each command. 
This is an issue since one of the commands in the pre-command  in the container runtime driver can be `module load` depending on the environment in which the workflow is running. Using `srun` on `module load` doesn't work so we'll need to either nor srun any command which uses module load or add an additional module section to the container runtime driver which the jinja template which the jinja can add to the script without srun.

**Comment by pagrubel** [comment]
@rstyd Can we close this issue now?

**Comment by pagrubel** [comment]
Closing this as is fixed in #471
