### ISSUE TITLE
Show copyContainer is a BEE extension to DockerRequirements

### ISSUE THREAD

**Issue by pagrubel** [lanl/BEE#470]
Rename copyContainer to BEE:copyContainer

**Comment by pagrubel** [comment]
To be consistent with the MPI Requirements it should be beeflow:copyContainer

**Comment by jtronge** [comment]
We may want to look into using a beeflow-specific container requirement. Something such as `beeflow:ContainerRequirement` that includes `copyContainer` and other container options that we use.

**Comment by pagrubel** [comment]
This has been satisfied with PR#480
