### ISSUE TITLE
Error when submitting a workflow if bee_workdir does not exist.

### ISSUE THREAD

**Issue by pagrubel** [lanl/BEE#488]
We get an error when submitting workflow and bee_workdir does not exist. 
This happens on me because when switching between versions for testing different branches I sometimes get rid of everything. 

This may be covered when creating a bee.conf using bee_cfg new, however, if a user were to modify the bee.conf for a new bee_workdir, I think the same thing would happen. 

We could just ask them if they want to create the path giving them the info of what directory would be created. That gives them the option to correct the bee.conf if there was a typo or press forward with creating the directory.
Error:
```
bee_client submit clamr clamr-wf.tgz clamr_wf.cwl clamr_job.yml
Traceback (most recent call last):
  File "/yellow/users/pagrubel/.cache/pypoetry/virtualenvs/beeflow-ApM-ipUD-py3.8/bin/bee_client", line 2, in <module>
    from beeflow.client.bee_client import main
  File "/yellow/users/pagrubel/BEE/BEE_Private/src/beeflow/client/bee_client.py", line 14, in <module>
    bc.init()
  File "/yellow/users/pagrubel/BEE/BEE_Private/src/beeflow/common/config_driver.py", line 97, in init
    cls.CONFIG = VALIDATOR.validate(config)
  File "/yellow/users/pagrubel/BEE/BEE_Private/src/beeflow/common/config_validator.py", line 45, in validate
    raise ValueError(
ValueError: DEFAULT::bee_workdir: path "/users/pagrubel/.beeflow" does not exist
```

**Comment by pagrubel** [comment]
This also happens when invoking beeflow when bee_workdir does not exist.

**Comment by jtronge** [comment]
This happens because the validation code only checks whether the workdir exists or not. One way to fix it is to just create the directory during validation.

**Comment by pagrubel** [comment]
@jtronge Can you please fix it
