### ISSUE TITLE
bee-image-builder errors

### ISSUE THREAD

**Issue by quellyn** [lanl/BEE#5]
Hi guys,

So I wanted to try out BEE on my laptop. It's a MacBook Air, so not the beefiest of boxes. I decided to build a virtual machine and run BEE in that.

After a couple of false starts (I couldn't use VirtualBox, as it doesn't support nested virtualization), I used VMware Fusion to build a CentOS 7.4 virtual machine. Then I downloaded the BEE-master.zip file from https://github.com/lanl/BEE and followed the instructions at https://github.com/lanl/BEE/blob/master/doc/User%20Guide%20for%20BEE-VM.md

In addition to packer, I had to install some more software along the way (kvm, python-pip, qemu, seabios-bin, etc). Once I got that done, I was able to successfully run the initial setup script (install.sh). Then I moved on to trying to build a BEE base image (build_bee_vm.sh). That errored out.

I determined that the sample JSON file being used (ubuntu1404-qemu-template.json) was coded to use more resources than my little laptop could provide (16 cpus, 8GB memory, 65G disk space). I changed those to much more modest figures and ran again. I got farther along this time before it errored out. Eventually I attached a vncviewer session to watch the build. I saw that it was getting as far as the Ubuntu 14.04 installation screen, but that the process seemed to be stuck waiting on user input. I could manually "drive" the installation, but the Packer automation seemed to be broken.

Any ideas on what's going on would sure be welcome! I am stumped. I'm attaching a few files to this that I hope will help figure out the issue:

1. A diff file showing my modifications to the templates and a couple other files
2. The output from my build attempt
3. A screen shot showing the Ubuntu installer window in vncviewer.

Thanks,
Quellyn Snead

[quellyns-mods.txt](https://github.com/lanl/BEE/files/1516137/quellyns-mods.txt)

[build.out.txt](https://github.com/lanl/BEE/files/1516135/build.out.txt)

![build_bee_vm sh-screenshot](https://user-images.githubusercontent.com/33294773/33407344-35a40552-d52e-11e7-991f-1d64e1b76cf3.jpg)

**Comment by cjy7117** [comment]
Hi Quellyn,

Thanks for the feedback.
I looked into your build out file. It seems that the packer had trouble connecting to the VM via SSH. I think this may caused by some network or security configuration issue that is preventing the VM from using the port 22. You might need to look into that of your VMware virtual machine. Also, you can try it on the Galton nodes of the Darwin testbed. 

Thanks,

Jieyang Chen

**Comment by quellyn** [comment]
Hey Jieyang,

I think the SSH connection errors are a side effect because the Ubuntu 14.04 VM doesn’t even exist at that point. My vnc session shows the Ubuntu installer start up and then hang waiting on user input. That’s why I said I can manually drive the install — in other words, I can use the vnc window to answer the installer prompts and install the machine. 

It’s like Packer is not sending the right responses. It could be something related to my nested virtualization setup — although I’m not sure why since like I said, I can manually drive the installer.

I was planning to try it out on some real hardware next. I’ll let you know !

Q

**Comment by quellyn** [comment]
Update:  The error was mine. I was running my vncviewer without specifing that the connection was shared (between the viewer and the Ubuntu installer).

Closing ...

**Comment by pagrubel** [comment]
THis is a duplicate sorry
