### ISSUE TITLE
Builder Errors

### ISSUE THREAD

**Issue by jtronge** [lanl/BEE#550]
When the builder encounters certain errors, such as a Dockerfile not existing, etc., it will simply print a warning and the workflow will continue. This makes it difficult to figure out why a workflow isn't working and the builder's error message gets buried in the log. For example I tried running the `examples/clamr-ffmpeg-build` workflow and the builder printed a warning `[01;33mWARNING: There was a problem executing dockerFile![0m`. The workflow continued and just didn't produce any output files.

This is slightly related to issue #485, but I thought it was best to create a new one.

**Comment by pagrubel** [comment]
I'm not saying this is the best approach, however the builder was meant to be very flexible, so if it fails there is a chance that a container still exists. So I guess he was trying to continue the workflow. We will need to decide what errors should be generated to stop the workflow or at least the task.
