### ISSUE TITLE
Check if beeflow is running in cli.py

### ISSUE THREAD

**Issue by jtronge** [lanl/BEE#553]
I realized that my updates to cli.py aren't properly checking if beeflow is running before starting it again. Ideally it should check if the beeflow socket already exists before launching. I'll try to fix this in a PR soon.

**Comment by pagrubel** [comment]
@jtronge Was this fixed?

**Comment by jtronge** [comment]
Yes, I think I might of merged this in with a different pr. It looks like cli.py is now checking this.
