### ISSUE TITLE
Broken Slurm Unit Test

### ISSUE THREAD

**Issue by jtronge** [lanl/BEE#559]
One of the unit tests `test_cancel_bad_job_id` is broken in CI for some reason. It seems to work locally on both darwin and fog, so I'm assuming that this is a problem with the Slurm version.

One way to fix this would be to build Slurm manually in CI. However this might make the jobs take even longer. We could also launch everything in a docker container or just wait until ubuntu updates their Slurm version.

**Comment by pagrubel** [comment]
@jtronge Has this been fixed? If so please close it

**Comment by jtronge** [comment]
I ended up removing this test because it doesn't seem like Slurm defines this very well. If you try to run `scancel` with a bad job id it seems to always return 0, no matter what.
