### ISSUE TITLE
Need to load the charliecloud module before beeflow start

### ISSUE THREAD

**Issue by rstyd** [lanl/BEE#580]
The workflow manager requires charliecloud to start up an instance of neo4j. In order to do this, charliecloud needs to be loaded into the environment when the workflow manager is started in `beeflow start`. We should add some code to check if `ch-run` or some other charliecloud command exists when `beeflow start` runs, and if it doesn't attempt to load the module with lmod. If we can't get it there, then we should just exit with an error stating BEE requires charliecloud to run.

**Comment by jtronge** [comment]
What's the minimal version of Charliecloud we need? We could also check that here.

**Comment by pagrubel** [comment]
Right now I think the minimum is 0.27, but that could change esp. if we support squashfs. Do we want to keep up with that here and in the documentation?

**Comment by jtronge** [comment]
It might be good to check that, otherwise users might start a workflow and not realize something's wrong until it fails and prints something in the logs.

**Comment by pagrubel** [comment]
I'm in favor of saying version 0.29 just to make sure we start with that. It's easy to install. What do you think @rstyd 
Also whatever you implement fix the documentation to match it.

**Comment by rstyd** [comment]
Just bumping this issue since we're talking about it again.

**Comment by pagrubel** [comment]
If charliecloud isn't available we decided we would add the url for Charliecloud installation (maybe they just need to add a path, so that could also be in the message).

**Comment by pagrubel** [comment]
Addressed in #716
