### ISSUE TITLE
Add beeflow clean command

### ISSUE THREAD

**Issue by rstyd** [lanl/BEE#581]
At the moment, we have `beeflow stop` which kills all the BEE components and does _some_ cleaning. We should add a `beeflow clean` command that cleans up all the extra pieces that hang around including the log files, the workflow GDB, task manager GDB, and anything else that hangs around the `.beeflow` directory.

**Comment by pagrubel** [comment]
We may want to have an option to back up some of the information especially logs, also make sure they really meant to do a clean.

**Comment by pagrubel** [comment]
Is this the same as reset?  Was this addressed in #724? @aquan9 Do you think we can close this?

**Comment by rstyd** [comment]
Hey Pat I think this qualifies as a duplicate issue, and I'll close it.
