### ISSUE TITLE
Jinja should be attached to workflow (maybe even task) also would need to be archived

### ISSUE THREAD

**Issue by pagrubel** [lanl/BEE#595]

**Comment by pagrubel** [comment]
@jtronge Should we close this issue, since the jinja file is internal.

**Comment by jtronge** [comment]
I think so. The Jinja file is completely gone now. Each worker submits jobs in a different way and they all have their own mechanism for generating the job script. The Flux worker actually doesn't even generate a job script, since it calls directly into the Python API.
