### ISSUE TITLE
Resilience: Add to the Task Manager

### ISSUE THREAD

**Issue by rstyd** [lanl/BEE#614]
The task manager needs increased resilience in case of any unexpected service interruptions. We will accomplish this using the task manager database to spin workflows back up in case of any expected or unexpected downtime. For the the task manager, we need to rebuild the submit and job queues, check the status of any tasks that were running via slurm, and resubmit any failed tasks. The task manager will need to ensure that the workflow manager is back up before restarting tasks. 

This issue was originally part of #591, but we're breaking that issue into two.

**Comment by pagrubel** [comment]
Do issues #674-676 cover this can we close this?

**Comment by aquan9** [comment]
Closing this task, per discussion on April 9th. All parts of this task are in other tasks.
