### ISSUE TITLE
Merge submit and start client commands into one

### ISSUE THREAD

**Issue by jtronge** [lanl/BEE#622]
The new merged command should return the workflow ID immediately, spawning some sort of background thread to launch neo4j and then start the workflow.

**Comment by jtronge** [comment]
One problem with this is that the user won't see if the parser failed immediately. They would have to check the status or look at the logs to catch an error.

**Comment by pagrubel** [comment]
Could we have a no-start option and keep a start option?

**Comment by pagrubel** [comment]
Something like:
submit (automatically starts)
submit --no-start

**Comment by pagrubel** [comment]
Feature added in #653
