### ISSUE TITLE
Enable Modifying BEE Config and Workdir Location

### ISSUE THREAD

**Issue by rstyd** [lanl/BEE#624]
Currently, we're limited on the location of the BEE config file and bee workdir file. We need to modify `beeflow` to support changing these at startup and adding this information to the workflow DB so that it can be carried into the workflow manager.

**Comment by pagrubel** [comment]
It needs to be flexible enough to use two locations in the same $HOME space. For instance at OLCF summit and crusher share the same home space. However Summit is power 9 architecture and uses LSF, while Crusher (and Frontier) are Cray and use Slurm

**Comment by pagrubel** [comment]
bee_workdir is now configurable so I think we should close this issue and open a new one. However, I need some clarification:
At what point do we use the configuration file. Would it be possible to have a flag for beeflow --config and beeflow start to use a different location for the configuration file?

**Comment by pagrubel** [comment]
Closing this issue, if we still think we need to have a different location for bee.conf open another issue. It would probably have to use a flag since we would need to know the location as soon as we start up beeflow.
