### ISSUE TITLE
Checkpoint/Restart is broken

### ISSUE THREAD

**Issue by pagrubel** [lanl/BEE#631]
When testing the latest PR it seems that the checkpoint/restart was not working. 
We need to explore what is happening  and also create a test for it even if it is just to run manually.
Also we need to consider what to do with outputs stdout and stderr that may already exist for steps that are created due to checkpointing.

**Comment by jtronge** [comment]
For stdout/stderr maybe we should append to the output file. We might also be able to do something based on a numbering scheme (like clamr-stdout-0.txt, clamr-stdout-1.txt, ...) but that might be a little more complicated to handle.

Right now I think each restart task will overwrite the previous output. I think if we add `--open-mode=append` as an sbatch directive it might work.

**Comment by jtronge** [comment]
This should have been fixed in PR #680.
