### ISSUE TITLE
Sphinx Dependency Problem

### ISSUE THREAD

**Issue by jtronge** [lanl/BEE#647]
For some reason sphinx is causing `poetry update` to run forever. Running with `-vvv`, it seems to get stuck on `sphinxcontrib.applehelp`. I tried a few different versions of sphinx and they all seem to cause the same problem. I'm guessing there's another package causing a conflict.

**Comment by pagrubel** [comment]
@jtronge Can this issue be closed with the merge of #646

**Comment by pagrubel** [comment]
Closing this issue which was fixed in #647
