### ISSUE TITLE
Using "bee_client listall" before any workflows have been run

### ISSUE THREAD

**Issue by pagrubel** [lanl/BEE#658]
While setting up the tutorial in an instance I did a "beeclient listall" and it created an error. I don't think we usually see this since we list after some workflows are submitted. We should consider fixing it to check.

**Comment by rstyd** [comment]
I was looking to fix this issue, and I believe it's working as intended. 
I tried listall with a fresh BEE setup and I got `There are currently no workflows.`. 
Can you verify that for me @pagrubel?

**Comment by pagrubel** [comment]
@rstyd I closed this issue since it doesn't apply anymore
