### ISSUE TITLE
beeclient submit: interpret MAIN_CWL and YAML arguments as paths relative to ${PWD}

### ISSUE THREAD

**Issue by gaber** [lanl/BEE#661]
At the moment, `beeclient submit` seems to expect its MAIN_CWL and YAML arguments to be specified relative to WF_PATH. That's understandable, but it imposes a little extra friction in submitting a new workflow: I can't rely on my shell to auto-complete those filenames.

Could `beeclient submit` instead behave something like
```
Usage: beeclient submit [OPTIONS] WF_NAME MAIN_CWL YAML WORKDIR
```
i.e., where MAIN_CWL, YAML, and WORKDIR are all specified as either absolute pathnames or as pathnames relative to ${PWD}?

**Comment by pagrubel** [comment]
Since we also accept a packaged tar ball, we will have to consider getting rid of that option. I don't think we need it. If the user has a tar of the cwl to use put it on them to untar and use it so the MAIN_CWL and YAML files can be detected.

**Comment by jtronge** [comment]
I wonder if we could keep the input yaml file outside of the workflow directory. This would allow for tab completion and make it easier to have multiple input files for different runs.

**Comment by pagrubel** [comment]
As long as we make sure we put it in the archive that would work.

**Comment by pagrubel** [comment]
Discussion during March 13 meeting.
We discussed that we may want to parse the cwl in the client instead of the wfm, however it is intertwined with the gdb. 
Also, do the files need to be in the directory as we now require?

**Comment by pagrubel** [comment]
Client parses the workflow and passes it to the WFM. The submit would be just tell the path to the main  and require all the cwl to be in the same directory and full path for yml. We need to preserve the yml  in .beeflow/workflows/<wf_id> somewhere.

**Comment by pagrubel** [comment]
There is a discussion on our mattermost channel where we decided we could make a quick fix for this without parsing cwl in the client and make that a separate issue.  
Right now we tar the entire directory that the cwl file is in. This could be quite expensive if the user has other files in that dir, thus the need for parsing the cwl first and only archiving the files needed. For now we will add the yml file to the directory (in memory) and continue to archive the entire directory from the path to the main cwl file.

**Comment by pagrubel** [comment]
Maybe archive the command also

**Comment by pagrubel** [comment]
Assigning this to @Boogie3D and moving it to Burly Baracuda board in hopes we can get it in the next release

**Comment by Boogie3D** [comment]
I think there are two possible solutions that may be satisfactory:

1. Take MAIN_CWL and YAML as relative or absolute paths and remove the WORKDIR argument; assume the parent directory of MAIN_CWL is the WORKDIR to be tarballed. (We don't need to make this assumption for YAML.)
2. Remove the MAIN_CWL argument and instead supply it via an interactive prompt that supports autocompletion relative to WORKDIR

Each approach has certain strengths and weaknesses. E.g. 1. is more flimsy and bug-prone, and may require extra caution when implementing; 2. is more explicit and safe, but slightly less convenient for the user. Personally, I lean towards 2. but we can discuss it more.

**Comment by pagrubel** [comment]
Discussion from April 5 meeting: It should work like most apps where the files are either relative or full path
beeclient submit <name> <cwl_dir_path> <main_cwl_file_path> <yml_file_path> <wf_workdir or context dir>

**Comment by pagrubel** [comment]
beeclient submit <wf-name> <cwl_dir_path> <main_cwl_file_path> <yml_file_path> <wf_workdir or context dir>

**Comment by pagrubel** [comment]
beeclient submit "wf-name" <cwl_dir_path> <main_cwl_file_path> <yml_file_path> <wf_workdir or context dir>

**Comment by pagrubel** [comment]
or
beeclient submit "wf-name"  <main_cwl_file_path> <yml_file_path> <wf_workdir or context dir>

and use the directory path for the main_cwl_file as the cwl inputs dir

**Comment by Boogie3D** [comment]
For now we'll go with a third option which is to accept the <wf_dir_path>, <main_cwl_file_path>, and <yml_file_path> each as relative or absolute paths. Obviously, this won't have any effect when the <wf_dir_path> is to a .tgz.
