### ISSUE TITLE
Task Manager Resiliency: Rebuild the submit and job queues when the task manager comes back up.

### ISSUE THREAD

**Issue by aquan9** [lanl/BEE#674]
Pieces broken up from #614

**Comment by jtronge** [comment]
Does this already happen on restart? It looks like the task manager is just loading up the old database file, which should still have the submit and job queue data, unless the whole database gets deleted.

**Comment by jtronge** [comment]
I did some testing with `examples/clamr-ffmpeg-build` and it looks like the task manager is able to recover the submit/job queues after failures and successfully update task states. I'm going to close this for now.
