### ISSUE TITLE
Task Manager Resiliency: Check the status of any tasks that were running via slurm. Resubmit any failed tasks.

### ISSUE THREAD

**Issue by aquan9** [lanl/BEE#675]
Pieces broken up from #614

**Comment by pagrubel** [comment]
Should this be optional or automatic?
Should there be a configuration option that only tries x number of times?

**Comment by jtronge** [comment]
I wonder if checkpoint-restart would affect this? We might want to only resubmit tasks if the `num_tries` in `beeflow:CheckpointRequirement` allows it. I'm not sure if the number of times a task has already been restarted is stored in a database, so we might lose it on task manager failure.

**Comment by pagrubel** [comment]
I think this issue needs some discussion and clarification, maybe during a meeting.

**Comment by jtronge** [comment]
Resolved with PR #827
