### ISSUE TITLE
bee_orc_ctl.py no longer runs on darwin

### ISSUE THREAD

**Issue by pagrubel** [lanl/BEE#7]
when running bee_orc_ctl.py I get the following. 
Traceback (most recent call last):
  File "/home/pagrubel/github/BEE/bee-launcher/bee_orc_ctl.py", line 9, in <module>
    from bee_os_launcher import BeeOSLauncher
  File "/home/pagrubel/github/BEE/bee-launcher/bee_os_launcher.py", line 14, in <module>
    from keystoneauth1 import loading
ImportError: No module named keystoneauth1

It works if I go back to commit 3692c03d8a5c091ad0bb011bd12f0693c4732ea0
I'll do a git bisect to see where this starts

**Comment by pagrubel** [comment]
The result of the bisect
d2b2145bfb513c5d53bd02a93764abfc1a36bd76 is the first bad commit

**Comment by cjy7117** [comment]
Pat, I imported several additional modules for the OpenStack Launcher. Please run the install.sh again to install the additional modules. It should work.

**Comment by pagrubel** [comment]
okay I'll try that

**Comment by pagrubel** [comment]
that works I'll close the issue. Thanks, Jieyang!

**Comment by pagrubel** [comment]
bee_launcher.py -l lammps
Traceback (most recent call last):
  File "/home/pagrubel/github/BEE/bee-launcher/bee_launcher.py", line 130, in <module>
    main(sys.argv[1:])
  File "/home/pagrubel/github/BEE/bee-launcher/bee_launcher.py", line 55, in main
    bee_launcher = BeeLauncher()
  File "/home/pagrubel/github/BEE/bee-launcher/bee_launcher.py", line 21, in __init__
    ns = Pyro4.locateNS(port = port, hmac_key = os.getlogin())
  File "/home/pagrubel/.local/lib/python2.7/site-packages/Pyro4/core.py", line 1907, in _locateNS
    raise e
Pyro4.errors.NamingError: Failed to locate the nameserver

**Comment by pagrubel** [comment]
After I got the deamon running I went to run the job and got the above error

**Comment by cjy7117** [comment]
Looks like the bee launcher has trouble finding the bee_orc_ctl. There are two possible causes: (1) you launch a task too early when the bee_orc_ctl is not completely started; (2) the bee launcher and bee_orc_ctl are running on two different nodes (machines), so they cannot connect to each other via localhost. They have to be run on the same node (machine).

**Comment by pagrubel** [comment]
I'll redo this today, but I believe I was doing the same thing that I did in the past (before your changes)

**Comment by pagrubel** [comment]
I got further. Do I need to redo Step 2. Build BEE-VM image
Output using galton nodes:
Not starting broadcast server for localhost.
NS running on localhost:46291 (127.0.0.1)
URI = PYRO:Pyro.NameServer@localhost:46291
Starting Bee orchestration controller..
/home/pagrubel/github/BEE/bee-launcher
Bee orchestration controller started.
Bee orchestration controller: received task creating request
Host[cn30]:killing all vms
['pkill', '-u pagrubel', 'qemu-system-x86']
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x pkill -u pagrubel qemu-system-x86
Host[cn31]:killing all vms
['pkill', '-u pagrubel', 'qemu-system-x86']
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn31 -x pkill -u pagrubel qemu-system-x86
[lammps-bee-master]: create new OS image.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x qemu-img create -b /home/pagrubel/.bee/base_img/base_img -f qcow2 /home/pagrubel/.bee/vm_imgs/img_lammps_0.qcow2
qemu-img: /home/pagrubel/.bee/vm_imgs/img_lammps_0.qcow2: Could not open '/home/pagrubel/.bee/base_img/base_img': No such file or directory
[lammps-bee-worker001]: create new OS image.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn31 -x qemu-img create -b /home/pagrubel/.bee/base_img/base_img -f qcow2 /home/pagrubel/.bee/vm_imgs/img_lammps_1.qcow2
qemu-img: /home/pagrubel/.bee/vm_imgs/img_lammps_1.qcow2: Could not open '/home/pagrubel/.bee/base_img/base_img': No such file or directory
[lammps-bee-master]: starting BEE-VM.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x qemu-system-x86_64 -vnc none -enable-kvm -m 16G -cpu host -smp cores=8,threads=1,sockets=2 -netdev socket,id=net,mcast=230.0.0.1:1234 -device virtio-net-pci,netdev=net,mac=02:00:00:00:0a:01 -netdev user,id=net0,hostfwd=tcp::5555-:22 -device virtio-net-pci,netdev=net0 -qmp tcp:cn30:6666,server,nowait -drive file=/home/pagrubel/.bee/vm_imgs/img_lammps_0.qcow2,cache=none,if=virtio -fsdev local,security_model=none,id=fsdev0,path=/home/pagrubel/share/bee_share -device virtio-9p-pci,id=fs0,fsdev=fsdev0,mount_tag=hostshare -monitor stdio

(process:27570): GLib-WARNING **: gmem.c:482: custom memory allocation vtable not supported
qemu-system-x86_64: -drive file=/home/pagrubel/.bee/vm_imgs/img_lammps_0.qcow2,cache=none,if=virtio: could not open disk image /home/pagrubel/.bee/vm_imgs/img_lammps_0.qcow2: Could not open '/home/pagrubel/.bee/vm_imgs/img_lammps_0.qcow2': No such file or directory
info snapshots
[lammps-bee-worker001]: starting BEE-VM.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn31 -x qemu-system-x86_64 -vnc none -enable-kvm -m 16G -cpu host -smp cores=8,threads=1,sockets=2 -netdev socket,id=net,mcast=230.0.0.1:1234 -device virtio-net-pci,netdev=net,mac=02:00:00:00:0a:02 -netdev user,id=net0,hostfwd=tcp::5555-:22 -device virtio-net-pci,netdev=net0 -qmp tcp:cn31:6666,server,nowait -drive file=/home/pagrubel/.bee/vm_imgs/img_lammps_1.qcow2,cache=none,if=virtio -fsdev local,security_model=none,id=fsdev0,path=/home/pagrubel/share/bee_share -device virtio-9p-pci,id=fs0,fsdev=fsdev0,mount_tag=hostshare -monitor stdio

(process:1412): GLib-WARNING **: gmem.c:482: custom memory allocation vtable not supported
qemu-system-x86_64: -drive file=/home/pagrubel/.bee/vm_imgs/img_lammps_1.qcow2,cache=none,if=virtio: could not open disk image /home/pagrubel/.bee/vm_imgs/img_lammps_1.qcow2: Could not open '/home/pagrubel/.bee/vm_imgs/img_lammps_1.qcow2': No such file or directory
info snapshots
[lammps-bee-master]: set hostname.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa root@localhost -x ' hostname lammps-bee-master '
[lammps-bee-worker001]: set hostname.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn31 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa root@localhost -x ' hostname lammps-bee-worker001 '
[lammps-bee-master]: set hosts file for MPI.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa root@localhost -x ' echo "192.168.10.1 lammps-bee-master" | tee --append  /etc/hosts '
[lammps-bee-worker001]: set hosts file for MPI.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn31 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa root@localhost -x ' echo "192.168.10.1 lammps-bee-master" | tee --append  /etc/hosts '
[lammps-bee-master]: set hosts file for MPI.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa root@localhost -x ' echo "192.168.10.2 lammps-bee-worker001" | tee --append  /etc/hosts '
[lammps-bee-worker001]: set hosts file for MPI.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn31 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa root@localhost -x ' echo "192.168.10.2 lammps-bee-worker001" | tee --append  /etc/hosts '
[lammps-bee-master]: mount shared directory (via 9p).
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa root@localhost -x ' mount -t 9p -o trans=virtio,msize=262144 hostshare /home/ubuntu/vmshare -oversion=9p2000.L '
[lammps-bee-worker001]: mount shared directory (via 9p).
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn31 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa root@localhost -x ' mount -t 9p -o trans=virtio,msize=262144 hostshare /home/ubuntu/vmshare -oversion=9p2000.L '
[lammps-bee-master]: update user UID.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa root@localhost -x ' usermod -u 28727 ubuntu '
[lammps-bee-master]: update user GID.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa root@localhost -x ' groupmod -g 28727 ubuntu '
[lammps-bee-master]: update ownership of shared directory.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa root@localhost -x ' chown -R ubuntu:ubuntu /home/ubuntu/vmshare '
[lammps-bee-master]: change eth0 mtu.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa root@localhost -x ' ifconfig eth0 mtu 15000 '
[lammps-bee-worker001]: update user UID.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn31 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa root@localhost -x ' usermod -u 28727 ubuntu '
[lammps-bee-worker001]: update user GID.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn31 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa root@localhost -x ' groupmod -g 28727 ubuntu '
[lammps-bee-worker001]: update ownership of shared directory.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn31 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa root@localhost -x ' chown -R ubuntu:ubuntu /home/ubuntu/vmshare '
[lammps-bee-worker001]: change eth0 mtu.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn31 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa root@localhost -x ' ifconfig eth0 mtu 15000 '
vm conf done
[lammps-bee-master]: pull docker image in parallel.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa ubuntu@localhost -x ' mpirun --mca btl_tcp_if_include eth0 -host lammps-bee-master,lammps-bee-worker001, docker pull pagrubel/lammps2_bee '
[lammps-bee-master]: start docker container.
['docker', 'run', '--name bee_docker', '--net=host', '-d', '--user root', '-v /home/ubuntu/vmshare:/mnt/docker_share', 'pagrubel/lammps2_bee', '/usr/sbin/sshd -D']
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa ubuntu@localhost -x ' docker run --name bee_docker --net=host -d --user root -v /home/ubuntu/vmshare:/mnt/docker_share pagrubel/lammps2_bee /usr/sbin/sshd -D '
[lammps-bee-master][Docker]: update docker user UID.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa ubuntu@localhost -x ' docker exec --user root bee_docker usermod -u 28727 root '
[lammps-bee-master][Docker]: update docker user GID.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa ubuntu@localhost -x ' docker exec --user root bee_docker groupmod -g 28727 root '
[lammps-bee-worker001]: start docker container.
['docker', 'run', '--name bee_docker', '--net=host', '-d', '--user root', '-v /home/ubuntu/vmshare:/mnt/docker_share', 'pagrubel/lammps2_bee', '/usr/sbin/sshd -D']
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn31 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa ubuntu@localhost -x ' docker run --name bee_docker --net=host -d --user root -v /home/ubuntu/vmshare:/mnt/docker_share pagrubel/lammps2_bee /usr/sbin/sshd -D '
[lammps-bee-worker001][Docker]: update docker user UID.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn31 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa ubuntu@localhost -x ' docker exec --user root bee_docker usermod -u 28727 root '
[lammps-bee-worker001][Docker]: update docker user GID.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn31 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa ubuntu@localhost -x ' docker exec --user root bee_docker groupmod -g 28727 root '
[lammps-bee-master]: copy file:/home/pagrubel/BEE/lammps/notes_and_scripts/run_lammps.sh --> /home/ubuntu/general_script.sh.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x scp -P 5555 -i /home/pagrubel/.bee/ssh_key/id_rsa -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null /home/pagrubel/BEE/lammps/notes_and_scripts/run_lammps.sh ubuntu@localhost:/home/ubuntu/general_script.sh
ssh: connect to host localhost port 5555: Connection refused
lost connection
[lammps-bee-master][Docker]: copy file to docker/home/ubuntu/general_script.sh --> /home/root/general_script.sh.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa ubuntu@localhost -x ' docker cp /home/ubuntu/general_script.sh bee_docker:/home/root/general_script.sh '
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa ubuntu@localhost -x ' docker exec --user root bee_docker chown root:root /home/root/general_script.sh '
[lammps-bee-master][Docker]: run script:/home/root/general_script.sh.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q -R 22223:localhost:22223 -R 22222:localhost:22222 pagrubel@cn30 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa -R 22223:localhost:22223 -R 22222:localhost:22222 ubuntu@localhost -x ' docker exec --user root bee_docker /home/root/general_script.sh '
docker conf done

**Comment by cjy7117** [comment]
Yes, once you run install.sh, it will delete all the old bee stuffs if exist that include the old base image. So you need to redo the image build.

**Comment by pagrubel** [comment]
I'm still having problems with the vm launcher. I'm going to close this issue though. I'll reopen it or another. I have a strong suspicion that its my problem though

**Comment by pagrubel** [comment]
@cjy7117 I went back to the last commit that works and everything works including my scripts and I was able to run the lammps program. Note: I'm still using the general script, but I don't think you changed anything there. 
Then I checkout out the current master, redid the install and step 2. By the way its in a different directory now so I am going to edit the guide. 

Here are the resulting problems:
Not starting broadcast server for localhost.
NS running on localhost:51439 (127.0.0.1)
URI = PYRO:Pyro.NameServer@localhost:51439
Starting Bee orchestration controller..
/home/pagrubel/github/BEE/bee-launcher
Bee orchestration controller started.
Bee orchestration controller: received task creating request
Host[cn30]:killing all vms
['pkill', '-u pagrubel', 'qemu-system-x86']
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x pkill -u pagrubel qemu-system-x86
[lammps-bee-master]: create new OS image.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x qemu-img create -b /home/pagrubel/.bee/base_img/base_img -f qcow2 /home/pagrubel/.bee/vm_imgs/img_lammps_0.qcow2
Formatting '/home/pagrubel/.bee/vm_imgs/img_lammps_0.qcow2', fmt=qcow2 size=68719476736 backing_file='/home/pagrubel/.bee/base_img/base_img' encryption=off cluster_size=65536 lazy_refcounts=off 
[lammps-bee-master]: starting BEE-VM.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x qemu-system-x86_64 -vnc none -enable-kvm -m 20G -cpu host -smp cores=8,threads=1,sockets=2 -netdev socket,id=net,mcast=230.0.0.1:1234 -device virtio-net-pci,netdev=net,mac=02:00:00:00:0a:01 -netdev user,id=net0,hostfwd=tcp::5555-:22 -device virtio-net-pci,netdev=net0 -qmp tcp:cn30:6666,server,nowait -drive file=/home/pagrubel/.bee/vm_imgs/img_lammps_0.qcow2,cache=none,if=virtio -fsdev local,security_model=none,id=fsdev0,path=/home/pagrubel/share/bee_share -device virtio-9p-pci,id=fs0,fsdev=fsdev0,mount_tag=hostshare -monitor stdio

(process:2796): GLib-WARNING **: gmem.c:482: custom memory allocation vtable not supported
QEMU 2.0.0 monitor - type 'help' for more information
(qemu) info snapshots
[lammps-bee-master]: set hostname.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa root@localhost -x ' hostname lammps-bee-master '
[lammps-bee-master]: set hosts file for MPI.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa root@localhost -x ' echo "192.168.10.1 lammps-bee-master" | tee --append  /etc/hosts '
[lammps-bee-master]: mount shared directory (via 9p).
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa root@localhost -x ' mount -t 9p -o trans=virtio,msize=262144 hostshare /home/ubuntu/vmshare -oversion=9p2000.L '
[lammps-bee-master]: update user UID.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa root@localhost -x ' usermod -u 28727 ubuntu '
[lammps-bee-master]: update user GID.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa root@localhost -x ' groupmod -g 28727 ubuntu '
[lammps-bee-master]: update ownership of shared directory.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa root@localhost -x ' chown -R ubuntu:ubuntu /home/ubuntu/vmshare '
[lammps-bee-master]: change eth0 mtu.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa root@localhost -x ' ifconfig eth0 mtu 15000 '
vm conf done
[lammps-bee-master]: pull docker image in parallel.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa ubuntu@localhost -x ' mpirun --mca btl_tcp_if_include eth0 -host lammps-bee-master, docker pull pagrubel/lammps2_bee '
[lammps-bee-master]: start docker container.
['docker', 'run', '--name bee_docker', '--net=host', '-d', '--user root', '-v /home/ubuntu/vmshare:/mnt/docker_share', 'pagrubel/lammps2_bee', '/usr/sbin/sshd -D']
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa ubuntu@localhost -x ' docker run --name bee_docker --net=host -d --user root -v /home/ubuntu/vmshare:/mnt/docker_share pagrubel/lammps2_bee /usr/sbin/sshd -D '
[lammps-bee-master][Docker]: update docker user UID.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa ubuntu@localhost -x ' docker exec --user root bee_docker usermod -u 28727 root '
[lammps-bee-master][Docker]: update docker user GID.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa ubuntu@localhost -x ' docker exec --user root bee_docker groupmod -g 28727 root '
[lammps-bee-master]: copy file:/home/pagrubel/share/bee_share/run_lammps.sh --> /home/ubuntu/general_script.sh.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x scp -P 5555 -i /home/pagrubel/.bee/ssh_key/id_rsa -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null /home/pagrubel/share/bee_share/run_lammps.sh ubuntu@localhost:/home/ubuntu/general_script.sh
Warning: Permanently added '[localhost]:5555' (ECDSA) to the list of known hosts.
Permission denied, please try again.
Permission denied, please try again.
Permission denied (publickey,password).
lost connection
[lammps-bee-master][Docker]: copy file to docker/home/ubuntu/general_script.sh --> /home/root/general_script.sh.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa ubuntu@localhost -x ' docker cp /home/ubuntu/general_script.sh bee_docker:/home/root/general_script.sh '
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q pagrubel@cn30 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa ubuntu@localhost -x ' docker exec --user root bee_docker chown root:root /home/root/general_script.sh '
[lammps-bee-master][Docker]: run script:/home/root/general_script.sh.
ssh -p 22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q -R 22223:localhost:22223 -R 22222:localhost:22222 pagrubel@cn30 -x ssh -p 5555 -o StrictHostKeyChecking=no -o ConnectTimeout=300 -o UserKnownHostsFile=/dev/null -q -i /home/pagrubel/.bee/ssh_key/id_rsa -R 22223:localhost:22223 -R 22222:localhost:22222 ubuntu@localhost -x ' docker exec --user root bee_docker /home/root/general_script.sh '
docker conf done

**Comment by pagrubel** [comment]
@cjy7117  I tried you flecsale example and had the same problem

**Comment by cjy7117** [comment]
Hi Pat,

I have been working on removing the hard-coded ssh keys in BEE, so I accidentally introduced a bug in the bee-vm image builder. Now, it has been fixed and we no longer need to store any ssh keys in the repo. 

Also, I made a change to the requirement to Docker images, since I noticed that some applications cannot run under root. So now BEE users need to create a non-root account in their Docker container and run everything using that account. For example, in our Dockerized flecsale, I created a non-root user 'beeuser'.

Thanks,

Jieyang

**Comment by pagrubel** [comment]
Closing this issue which was fixed by merge from master.

**Comment by trandles-lanl** [comment]
@pagrubel can this issue be closed?

**Comment by pagrubel** [comment]
yes I'm closing it
