### ISSUE TITLE
Delete Archived Workflows

### ISSUE THREAD

**Issue by Boogie3D** [lanl/BEE#700]
The BEE client should have a command to conveniently delete an archived workflow and any associated files from the `.beeflow` directory. Doing this manually can cause issues. Removing GDB files may cause issues as sometimes an orphaned Neo4j process seems to be accessing them even when all BEE components are down (this could be caused by something I did wrong, but if not then these rogue processes also need to be killed).

Possible commands are:
- `beeclient delete wf_id`
- `beeclient remove wf_id`

**Comment by pagrubel** [comment]
Archived workflows are in bee_workdir/archives. There are also files in bee_workdir/workflows.
Maybe put this off and discuss having a utility for bee_workdiir/archives like let them move them and some command to let them unpack a tar ball in a path they specify.

**Comment by pagrubel** [comment]
I think I'll add Cancelled workflows to this as well.

**Comment by pagrubel** [comment]
Addressed in #774
