### ISSUE TITLE
Command to Download Default Dependencies Container

### ISSUE THREAD

**Issue by Boogie3D** [lanl/BEE#702]
Rather than simply attempting to point users toward a usable BEE dependencies container, there could be a client command to download the container from DockerHub, etc using Charliecloud's `ch-image pull` command. We should decide whether we want to pull this into Charliecloud's local image repo and keep it there or convert it into a tarball and store on the filesystem. This method may not be usable on restricted networks, but those circumstances can be handled on a case-by-case basis by providing the appropriate environment on those machines.

Possible commands are:
- `beeclient pull`
- `beeclient pull-deps`
- `beeclient download-deps [dest_dir]` (default: `.`)
- `beeclient dependencies`

**Comment by pagrubel** [comment]
Could we have a github action that builds the container and push it to dockerhub. We would run this manually.

**Comment by pagrubel** [comment]
Addressed in PR #728
