### ISSUE TITLE
Restart GDB on Failure

### ISSUE THREAD

**Issue by Boogie3D** [lanl/BEE#704]
We should be able to detect when either the GDB process has stopped running or when the GDB container itself has stopped running and restart the container in either case. Main questions are:

- How to detect?
  - WorkflowInterface throws an error when it can't connect to the Neo4j interface. Is this sufficient or should we detect some other way?
- Which component(s) should be responsible for detection and for restarting?
- If somehow the container is still running but not the Neo4j process, should we just restart the process without restarting the container? Is this situation possible?

**Comment by pagrubel** [comment]
Addressed in #759
