### ISSUE TITLE
Review Stability of BEE Client

### ISSUE THREAD

**Issue by rstyd** [lanl/BEE#707]
We need to do some testing to figure out which bad user inputs can cause an error and add error messages for them. For example, what happens if a user tries to cancel or query a workflow that doesn't exist?

**Comment by pagrubel** [comment]
I think there are some issues that are related to this so we should also look through those and see which ones are still issues, maybe include them in here in a checklist and close the old issues (or close them when this is closed)

**Comment by rstyd** [comment]
After a thorough review of beeclient commands, I couldn't find any input that could cause issues. Great job, team!
