### ISSUE TITLE
Add Beeflow Reset Command

### ISSUE THREAD

**Issue by rstyd** [lanl/BEE#708]
We should add a beeflow reset command that resets the user's `.beeflow` directory of all workflows, clears all the database, and starts the application back to factory settings.

**Comment by pagrubel** [comment]
Convenient but a bit dangerous, I would say that we should have an option to archive it. They should be able to add a path for the archive probably on scratch or something. And definitely would need to have a big caution message, esp. if they choose not to archive it.

**Comment by rstyd** [comment]
Yeah there'll need to be a do you _really_ want do to this message. Archiving the storage could be interesting.
