### ISSUE TITLE
Cancel workflows leaves an orphaned neo4j instance

### ISSUE THREAD

**Issue by pagrubel** [lanl/BEE#730]
The neo4j pid should be in the wf manager database. The neo4j instance should be killed if a workflow is cancelled.

Also, should the workflow be left in the database with a CANCELLED status?

**Comment by pagrubel** [comment]
If some tasks finished, the user may want the workflow left in the database.

**Comment by pagrubel** [comment]
Also, as we fix this, evaluate if we should cancel workflows from ``beeflow core stop`` and/or ``beeflow core reset``

**Comment by jtronge** [comment]
A related problem is when someone submits a workflow but with the `--no-start` option. This will also leave an orphaned neo4j process, assuming that they don't eventually call `beeflow start` on the workflow.

**Comment by pagrubel** [comment]
This issue needs to be closed. We need to check everything above and see if we need to open other issues.

**Comment by pagrubel** [comment]
> A related problem is when someone submits a workflow but with the `--no-start` option. This will also leave an orphaned neo4j process, assuming that they don't eventually call `beeflow start` on the workflow.

This does leave a neo4j instance when beeflow is stopped using ``beeflow core stop``, but it isn't actually orpaned because after a ``beeflow core start`` the workflow can be started and it works (it can also be cancelled).

**Comment by pagrubel** [comment]
I'm closing this issue since PR #738 addresses this issue with orphaned neo4j instances. The related issue for ``beeflow core reset`` will be opened as a separate issue.
