### ISSUE TITLE
Neo4J Alternatives

### ISSUE THREAD

**Issue by pagrubel** [lanl/BEE#731]
### Discussed in https://github.com/lanl/BEE/discussions/505

<div type='discussions-op-text'>

<sup>Originally posted by **rstyd** August  1, 2022</sup>
We're currently using an older version of neo4j due to some issues we have with newer versions. This is kind of risky because we're going to reach a time (might already have) where the older version we're using is no longer supported and things could just break down the line. We need to either find a working solution with the newer versions of neo4j or look at pivoting to another graph database. 
 
I can't remember what all the issues were with moving to a newer version of neo4j. @Boogie3D Could you summarize those below? The primary difficulty in moving to another GDB is that Steven has written a massive amount of cypher code which is neo4j's proprietary query language which locks us in. 

Fortunately, neo4j has been working on open sourcing cypher and there are several competing GDBs with cypher support. These include [redis graph](https://redis.io/docs/stack/graph/), [agensgraph](https://github.com/bitnine-oss/agensgraph), and [memgraph](https://memgraph.com/docs/cypher-manual/). I propose we take some time to check out these alternatives. One nice thing about each of these is they can all support multiple GDBs running in the same instance which would make life much easier for our workflow management backend. 

</div>

**Comment by jtronge** [comment]
Closing this since we decided to stick with neo4j and upgrade to the new version (issue #817).
