### ISSUE TITLE
Documentation "typo" in Getting Started - Example Workflows section

### ISSUE THREAD

**Issue by kchilleri** [lanl/BEE#761]
In the _Getting Started - Example Workflows_ section under the _CLAMR workflow examples (containerized application)_ portion, there are two instances stating to use `bee config show` to list configuration file contents. I believe this needs to be changed to `beeflow config show` instead.

**Comment by pagrubel** [comment]
@kchilleri Feel free to submit a PR, if you think you might have other documentation changes you can give it a WIP label until you want it merged.

**Comment by kchilleri** [comment]
@pagrubel For the PR, which two branches should I choose for comparing changes?

**Comment by pagrubel** [comment]
Start with develop and create a new branch for your PR, it can be helpful to name it with the issue such as issue761/fix- ... so it has some meaning. This will be a small PR most likely but it is helpful to be meaningful (WIP stands for Work in Progress and those PR's don't run the tests. Hope this helps.

**Comment by pagrubel** [comment]
Addressed and merged in #763
