### ISSUE TITLE
Refactor the Task Manager

### ISSUE THREAD

**Issue by rstyd** [lanl/BEE#766]
We should refactor the task manager to make it easier to add improvements. It's been a long time since we've taken a good look at it, and it's become a bit crutfy as a result.

**Comment by jtronge** [comment]
To add some more detail: we should try to refactor the task manager code into multiple files to make it easier to manage. This would be along the lines of what was done in PR #532 for the workflow manager.

**Comment by pagrubel** [comment]
Closing this as done in #771
