### ISSUE TITLE
Update Developer's Guide: Installing and using poetry

### ISSUE THREAD

**Issue by pagrubel** [lanl/BEE#768]
It looks like we just included all poetry commands available instead of what we need for actually running BEE.
We should limit that to only what we need. As it is right now it is confusing.

Define the next step once the poetry environment is up?
We may also want to suggest starting a branch if you are actually starting development.

**Comment by aquan9** [comment]
I defined this on paper for @AnnaLeah02 Maybe this might be a good first issue for her?

**Comment by pagrubel** [comment]
Breaking this into two issues.

**Comment by Leahh02** [comment]
Need to include that in ~/.config/beeflow/bee.conf the neo4j_image should be changed to /projects/beedev/neo4j-5-17.tar.gz

**Comment by pagrubel** [comment]
Are you talking about in the documentation?

**Comment by Leahh02** [comment]
I am

**Comment by pagrubel** [comment]
That would be specific to LANL systems and the team so might not be appropriate

**Comment by Leahh02** [comment]
Oh ok, I won't add that to the documentation then

**Comment by pagrubel** [comment]
It would probably be advisable to put the version number without the specific location, also remember they can use the pull dependency options.

**Comment by Leahh02** [comment]
Gotcha, ok

**Comment by pagrubel** [comment]
Addressed in #899
