### ISSUE TITLE
Add Pre/Post Script Support

### ISSUE THREAD

**Issue by rstyd** [lanl/BEE#773]
Certain workflows require setup/teardown scripts that need to be run prior to and after a task. I propose we add a new ScriptRequirement that prepends and appends a script to the sbatch script that gets submitted to slurm. 

```
beeflow:ScriptRequirement:
    enabled: true    
    pre_file_path: pre_run.sh
    post_file_path: post_run.sh
```

The user would have to include the scripts in the workflow archive that they submit and put the path of the scripts relative to the workflow directory. They'd then be prepended/appended to the sbatch script generated in the slurm worker.

**Comment by pagrubel** [comment]
To make this most flexible I'm wondering if the scripts can be in a different location than the workflow directory, but we copy them to the directory before tarring it up, like we do for alternate yml and cwl files.

**Comment by kchilleri** [comment]
@pagrubel We can close this issue now, right?

**Comment by pagrubel** [comment]
yes
