### ISSUE TITLE
Add test (ci) when slurmrestd is not available

### ISSUE THREAD

**Issue by pagrubel** [lanl/BEE#823]
We have a path for systems that do not have slurmrestd. We need to test it and make sure it doesn't break.

**Comment by pagrubel** [comment]
Do we just want to set use_commands to True in the bee.conf file to test this.

**Comment by jtronge** [comment]
We might be able to test this with the integration CI. We would need to update `.github/workflows/integration.yml` to also test a slurm+commands instance. Right now that workflow runs two instances of the integration tests, one for slurm+slurmrestd and one for flux.

**Comment by aquan9** [comment]
This issue is complete for the Github actions CI. 

See the following in ci/bee_config.sh:
```
case $BEE_WORKER in
Slurmrestd)
    cat >> $BEE_CONFIG <<EOF
[slurm]
use_commands = False
openapi_version = $OPENAPI_VERSION
EOF
    ;;
SlurmCommands)
    cat >> $BEE_CONFIG <<EOF
[slurm]
use_commands = True
openapi_version = $OPENAPI_VERSION
EOF
    ;;
esac
```
