### ISSUE TITLE
Should we disable bee enhanced client

### ISSUE THREAD

**Issue by pagrubel** [lanl/BEE#835]
There is a security alert for lodash only used for the enhanced client. 
We haven't been using bee enhanced client so disabling should be okay.

**Comment by aquan9** [comment]
While discussing this in a meeting, Jake also agrees that this should be disabled. We haven't used it in over a year. It hasn't been put into use, and it just collects security vulnerabilities.

**Comment by pagrubel** [comment]
Addressed in #865
