### ISSUE TITLE
Add $SHELL Option to BEE ScriptRequirement

### ISSUE THREAD

**Issue by rstyd** [lanl/BEE#845]
We're currently making the unspoken assumption that BEE users will always prefer to use BASH for their `sbatch` scripts. That hasn't been an issue previously, but with the addition of the pre/post script support we have to ensure that the code within those scripts is interoperable with the `sbatch` script they will be embedded within. 

For this issue, we should add an additional option to the `beeflow:ScriptRequirement` that specifies which `$SHELL` the user prefers. I think this option should be the path to the `$SHELL` e.g. `/bin/bash`, `/bin/csh/`, `/bin/tcsh`.

**Comment by jtronge** [comment]
I'm thinking we might want to have this per-workflow rather than in the config file. I can see where some workflows would have to use csh for some code while bash for another one, as an example. Maybe it could be a part of `beeflow:ScriptRequirement`?

**Comment by pagrubel** [comment]
That sounds good. We could have default defined in the config though so that those who don't change do not have to specify it.

**Comment by kchilleri** [comment]
@rstyd have you pushed your code for this issue anywhere?

**Comment by kchilleri** [comment]
PR#856 closes this issue
