### ISSUE TITLE
Pre/Post Scripts should use the same $SHELL as defined in the BEE config

### ISSUE THREAD

**Issue by rstyd** [lanl/BEE#847]
This is a follow on to #845 and #846. Once we have a proper BEE shell configuration option and the sbatch scripts follow that, we'll need to ensure that the pre/post scripts also follow the `$SHELL` config.

@kchilleri is currently working on verifying that pre/post scripts have a shebang that defines _a_ `$SHELL` interpreter at parse time. We could additionally check after that the interpreter defined within that shebang matches the` $SHELL` defined in the BEE config and throw an error if it doesn't.

**Comment by kchilleri** [comment]
This must be done for both Slurm and Flux, right @rstyd ?
