### ISSUE TITLE
Enable Running Beeflow Submit from within a Workflow Directory

### ISSUE THREAD

**Issue by rstyd** [lanl/BEE#853]
Currently beeflow submit requires that workflow directory for a submission is not the current working directory. 

e.g. `beefolow submit workflow . ./wf.cwl ./job.yml  .` breaks. 

We'll need to figure out how to get this working. One particular issue is that the code which packages a directory into a workflow package for the workflow manager stores the intermediate tarball in the current working directory which means that the directory we're trying to tar is changing since tar is writing the file to that directory. This makes tar super unhappy. So, we'll want to move that step to a temporary directory.

**Comment by pagrubel** [comment]
Addressed in #854
