### ISSUE TITLE
Update Example Workflows: Clarify the $WORKDIR_PATH

### ISSUE THREAD

**Issue by Leahh02** [lanl/BEE#868]
When I was going through the cat-grep-tar workflow example it mentioned that to run the example I'd want to create a workdir for the workflow. I personally wasn't sure what the best practice was for where to put this workdir. 

It should be clarified that it should be outside of the BEE repo.

**Comment by Leahh02** [comment]
I tried to run make html and got 2 errors

Error 1:
Configuration error:
There is a programmable error in your configuration file

Error 2:
importlib.metadata.PackageNotFoundError: No package metadata was found for hpc-beeflow

make: *** [Makefile:20: html] Error 2

**Comment by pagrubel** [comment]
@AnnaLeah02 Did you try this in a poetry environement?

**Comment by Leahh02** [comment]
> @AnnaLeah02 Did you try this in a poetry environement?

I did

**Comment by Leahh02** [comment]
Krishna and I fixed it, I had to do "pip install hpc-beeflow" in my poetry environment.

**Comment by pagrubel** [comment]
Are you getting the proper version of the documentation when you build it though?

**Comment by pagrubel** [comment]
This has been addressed in #869
