### ISSUE TITLE
Forbid Workflow Workdir from being on /tmp or /var/tmp

### ISSUE THREAD

**Issue by rstyd** [lanl/BEE#870]
We need to prevent users from accidentally submitting a job with the workdir being on `/tmp` or `/var/tmp`. Both of these directories are local to the front end where the job is being submitted, so there's no way for them to be accessed on the compute node.

**Comment by kabir-vats** [comment]
Does this mean any directory with those names or specifically coming from a home directory?

**Comment by pagrubel** [comment]
> Does this mean any directory with those names or specifically coming from a home directory?

Those directories are in memory not physically on disk

**Comment by pagrubel** [comment]
Satisfied in #885
