### ISSUE TITLE
Check if neo4j and redis image are in their default location on the machine 

### ISSUE THREAD

**Issue by rstyd** [lanl/BEE#886]

**Comment by pagrubel** [comment]
Currently our documentation says this:
"For LANL systems, please use the containers supplied by the BEE team: /usr/projects/BEE/neo4j-3-5-17-ch.tar.gz, /usr/projects/BEE/redis.tar.gz "
So this should be what is checked for. You would need to check that they exist and available for read.

**Comment by pagrubel** [comment]
@rstyd Is this an issue for the config?

**Comment by rstyd** [comment]
Yes it would go into the config manager. Basically check those directories and set them up in the config if they do exist. And make sure users aren't asked to set them.

**Comment by pagrubel** [comment]
Shortly, I will hopefully be testing BEE on Venado and we will need a different container (arm based) for that. I would want to make sure it's name is understandable and different. We can also check for that once I set it up. I am fairly certain we can check if we are on an arm system.
