### ISSUE TITLE
Remove Shebang from Pre and Post scripts After Validation

### ISSUE THREAD

**Issue by rstyd** [lanl/BEE#890]
We need to remove the shebang part from the pre and post scripts since it interferes with the shebang at the beginning of the script. We also should ensure that it matches the SHELL option, but I'll make a separate issue for that since this is currently higher priority.

**Comment by kchilleri** [comment]
@rstyd PR #880 checks that the shell option defined in the cwl file matches the shebang line in the pre/post scripts, is this what you mean by the second sentence here?

**Comment by rstyd** [comment]
Yep that's exactly what I mean, but there is one caveat which is that we might want to account for if someone uses env. 

So, for example the shell option could be `/bin/bash/` but the scripts have ` #!/usr/bin/env bash`. We could either write that off as user error, or add an extra check.
