### ISSUE TITLE
DAG Enhancements

### ISSUE THREAD

**Issue by Leahh02** [lanl/BEE#921]
Brainstorm of ways to improve the `beeflow dag` command. 

- [x] Be able to make multiple versions of the workflow dag without overriding older versions. This should be similar to how `beeflow config new` works.
- [x] Make an argument or option for `beeflow dag` to specify where to save the dags to. Maybe this could be a dags directory in the user's workdir.
- [x] ~~Some kind of watch command to get a live view (discussion)~~ Added discussion #944 
- [x] Save the final dag in the workflow archive

- [x] Make the "depends on" arrows bold
- [x] ~~"beeflow core pull-deps" should pull neo4j and add the plugin - both ci and pull-deps should use a dockerfile in beeflow/data/dockerfiles/. maybe Dockerfile.neo4j also modify configuration for new dockerfile~~ see issue #943 
- [x] Figure out what to do with the graphmls directory
- [x] If when archiving the workflow and a dag does not exist, make one (this will happen for failed or if we decide to archive cancelled workflows)
- [x] Should we use the long wf_id?
- [x] Check to make sure there's a png in the archive

**Comment by pagrubel** [comment]
Do we want to use the entire wf_id for the png file, or maybe the wf_id-dag as a directory and store the multiple files in there?

**Comment by pagrubel** [comment]
Also, beeflow core pull-deps should build neo4j with the plugin using a dockerfile

**Comment by pagrubel** [comment]
Should the file names use the short wf_id?

**Comment by pagrubel** [comment]
Moving my recommendations up to the list.

**Comment by Leahh02** [comment]
Right now I'm making a directory that just has the graphmls after they've been exported by neo4j and I'm trying to figure out where they should go. Right now I have the graphmls directory inside the dags directory in .beeflow. 

I'm going to move the dags to a user specified location, but I'm not sure that the graphmls should go there too because they don't really serve a big purpose for the person looking at them. They can be helpful in trouble shooting if something is wrong with making the graph, but that's it. I could maybe move them to the workflow archive.

**Comment by pagrubel** [comment]
Closing this as all the enhancements have either been done or a separate issue has been made.
