### ISSUE TITLE
poetry.lock file in .gitignore

### ISSUE THREAD

**Issue by trandles-lanl** [lanl/BEE#93]
Is there a reason the poetry.lock file is in .gitignore in the master branch? According the the poetry documentation it is a GOOD thing to put poetry.lock into version control:

https://poetry.eustace.io/docs/basic-usage/#commit-your-poetrylock-file-to-version-control

Unless someone can tell me a really good reason to keep poetry.lock in .gitignore, I'm going to remove it from the .gitignore, commit .gitignore and poetry.lock to master, and cherry pick the commit to all of the open branches.

**Comment by trandles-lanl** [comment]
I'm going through ancient issues. Can this be closed? Shall we just continue working the way we have, or should some change be made to how poetry.lock is handled? @Boogie3D @qwofford

**Comment by Boogie3D** [comment]
@trandles-lanl I'm still of the opinion that committing poetry.lock would be a good thing to prevent bugs or testing problems due to version inconsistencies. I think we should bring it up at the next meeting and decide then and there what to do.

**Comment by pagrubel** [comment]
@jtronge is going to look at this

**Comment by rstyd** [comment]
poetry.lock has been added to the repo.
