### ISSUE TITLE
Do not allow ```beeflow core start``` from compute node

### ISSUE THREAD

**Issue by kchilleri** [lanl/BEE#932]
If environment variables SLURMD_* exist, then you are on a compute node. Do not allow beeflow to start and print out warning.

**Comment by pagrubel** [comment]
I'm wondering if that environment variable only exists on systems with slurmrestd. It might be better just to check for any SLURM in the environment

**Comment by kchilleri** [comment]
Need PR #933 - add check for different front end to be merged first.
