### ISSUE TITLE
Fix "beeflow core pull-deps" to use a Dockerfile to pull the neo4j container and add the apoc file

### ISSUE THREAD

**Issue by pagrubel** [lanl/BEE#943]
beeflow core pull-deps should use a Dockerfile to build the needed neo4j container and add the apoc file

This dockerfile should be placed in beeflow/data/dockerfiles and should be used by the ci integration tests so we only need to modify it in one place.

Also, if a user uses "beeflow core pull-deps" to have their own dependent containers, they should be used in the bee.conf file. Consider automatically editting it and removing the ~/.beeflow/deps directory.  Beeflow should not be running when this is done, so adding a check for that should probably be done.

**Comment by Leahh02** [comment]
Addressed by PR #945
