### ISSUE TITLE
If beeflow is started on a compute node and the allocation is stopped before beeflow is stopped it cannot be started up again

### ISSUE THREAD

**Issue by pagrubel** [lanl/BEE#956]
This shouldn't occur by the user, we only added the -B flag to ``beeflow core start`` for CI purposes. However, someone might start beeflow from a compute node anyway. In my case the wf_manager would not start and then I couldn't do a ``beeflow core stop``. We should make it easier to recover from that.  I was able to do so by deleting client.db, but that doesn't seem like the best route.

I guess this is not a priority, just wanted to put it on the radar screen.

**Comment by kchilleri** [comment]
Duplicate of issue #974.
