### ISSUE TITLE
Stuck initializing due to neo4j authorization

### ISSUE THREAD

**Issue by Leahh02** [lanl/BEE#959]
I got stuck initializing when I was working on develop after I deleted my .beeflow directory.

I went back to commit 9135e885 and I'm fine. Here's the order of everything I did:
removed the .beeflow directory, removed my poetry environment, and started fresh from commit 9135e885. Running a workflow was fine from there. Then I stopped beeflow and my poetry environment, and checkout the most recent commit. Removed the poetry environment, made a new one, made a new config, and started beeflow up. At that point I was able to run things without a problem
I did this with every commit until I got to one that worked.
So, I think the issue is coming from commit d0e68fbfee610277687a6510a8bacf0a8d050c73. If you already have a .beeflow directory and you're working from that commit forward, you're fine, but if you don't, you get stuck initializing

**Comment by pagrubel** [comment]
We reverted the fix to password, and that fixes this problem. However, we need a better password solution and I'm going to keep this open to remind us to check this once that seems fixed.

**Comment by rstyd** [comment]
Resolved by #962. Need to make sure final implementation of #772 doesn't bring this back.
